version: '3.5'

services:

  conductor-server:
    image: flaviostutz/conductor-server:2.12.1.6
    restart: always
    ports:
      - 8080:8080
    environment:
      - DYNOMITE_HOSTS=dynomite:8102:us-east-1c
      - ELASTICSEARCH_URL=http://elasticblast:8200/
      - LOADSAMPLE=true
      - PROVISIONING_UPDATE_EXISTING_TASKS=false

  conductor-ui:
    image: flaviostutz/conductor-ui
    restart: always
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    ports:
      - 5000:5000

  elasticblast:
    image: flaviostutz/elasticblast
    restart: always
    ports:
      - 8200:8200
    environment:
      - LOG_LEVEL=info
      - BLAST_URL=http://blast:6000

  blast:
    image: flaviostutz/blast-indexer
    ports:
      - 6000:6000
    volumes:
      - blast:/data

  dynomite:
    image: flaviostutz/dynomite:0.7.5
    restart: always
    ports:
      - 8102:8102
    volumes:
      - dynomite:/var/lib/redis

volumes:
  blast:
    driver: local
  dynomite:
    driver: local
